"""baseline

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-09 12:51:33.130371

The schema production actually has today: character_strokes, dictionary_entry (without
hsk_level/pos_tags — see 0002), study_item, review_log, study_item_history. Written by hand to
match production byte-for-byte, one statement per constraint, rather than autogenerated — this is
the version scripts/migrate.py stamps existing databases at (see backend/AGENTS.md), so its
own statements never run against them; only a brand-new database actually executes this file.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        CREATE TABLE IF NOT EXISTS dictionary_entry (
            id          BIGINT       NOT NULL AUTO_INCREMENT,
            simplified  VARCHAR(64)  NOT NULL,
            pinyin      VARCHAR(191) NOT NULL,
            definitions JSON         NOT NULL,
            PRIMARY KEY (id),
            KEY ix_dictionary_entry_simplified (simplified),
            KEY ix_dictionary_entry_pinyin (pinyin)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS character_strokes (
            `character` VARCHAR(8)  NOT NULL,
            has_data    TINYINT(1)  NOT NULL,
            strokes     JSON        NULL,
            medians     JSON        NULL,
            PRIMARY KEY (`character`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS study_item (
            id               BIGINT      NOT NULL AUTO_INCREMENT,
            entry_id         BIGINT      NOT NULL,
            card_state       SMALLINT    NOT NULL,
            card_stability   DOUBLE      NULL,
            card_difficulty  DOUBLE      NULL,
            card_due         DATETIME(6) NOT NULL,
            card_last_review DATETIME(6) NULL,
            created_at       DATETIME(6) NOT NULL,
            PRIMARY KEY (id),
            UNIQUE KEY uq_study_item_entry (entry_id),
            KEY ix_study_item_card_due (card_due),
            CONSTRAINT fk_study_item_entry FOREIGN KEY (entry_id)
                REFERENCES dictionary_entry (id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS review_log (
            id              BIGINT      NOT NULL AUTO_INCREMENT,
            study_item_id   BIGINT      NOT NULL,
            rating          SMALLINT    NOT NULL,
            review_datetime DATETIME(6) NOT NULL,
            PRIMARY KEY (id),
            KEY ix_review_log_study_item (study_item_id),
            CONSTRAINT fk_review_log_study_item FOREIGN KEY (study_item_id)
                REFERENCES study_item (id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS study_item_history (
            id               BIGINT      NOT NULL AUTO_INCREMENT,
            study_item_id    BIGINT      NOT NULL,
            created_at       DATETIME(6) NOT NULL,
            entry_id         BIGINT      NOT NULL,
            card_state       SMALLINT    NOT NULL,
            card_stability   DOUBLE      NULL,
            card_difficulty  DOUBLE      NULL,
            card_due         DATETIME(6) NOT NULL,
            card_last_review DATETIME(6) NULL,
            PRIMARY KEY (id),
            KEY ix_study_item_history_item_created (study_item_id, created_at),
            CONSTRAINT fk_study_item_history_study_item FOREIGN KEY (study_item_id)
                REFERENCES study_item (id),
            CONSTRAINT fk_study_item_history_entry FOREIGN KEY (entry_id)
                REFERENCES dictionary_entry (id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TABLE IF EXISTS study_item_history")
    op.execute("DROP TABLE IF EXISTS review_log")
    op.execute("DROP TABLE IF EXISTS study_item")
    op.execute("DROP TABLE IF EXISTS character_strokes")
    op.execute("DROP TABLE IF EXISTS dictionary_entry")
